language: node_js
node_js:
- stable
branches:
  only:
  - master
before_install:
- git config --global user.name "vboar"
- git config --global user.email "vboar@live.com"
- openssl aes-256-cbc -K $encrypted_ffa94ce55f12_key -iv $encrypted_ffa94ce55f12_iv -in id_rsa.enc -out id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
install:
- npm install hexo-cli -g
- npm install
script:
- hexo clean
- hexo generate && rsync -az -vv --delete -e 'ssh -o stricthostkeychecking=no' public/ ubuntu@kasswang.cn:/var/www/wiki
addons:
  ssh_known_hosts: kasswang.cn